CREATE DATABASE IF NOT EXISTS dbdesa;

use dbdesa;

CREATE TABLE IF NOT EXISTS users (
   id INT AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(255) NOT NULL UNIQUE,
   password CHAR(60) NOT NULL
);
